name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin # 사용할 Java 분배판 지정

      # 3. Build with Gradle
      - name: Grant execute permissions for Gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # 4. Log in to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 5. Delete existing image from ECR
      - name: Delete existing image from ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_URI: ${{ secrets.ECR_URI }}
        run: |
          IMAGE_TAG=latest
          aws ecr batch-delete-image \
            --repository-name demo \
            --image-ids imageTag=$IMAGE_TAG || echo "No existing image found."

      # 6. Build Docker image
      - name: Build Docker image
        run: docker build -t demo .

      # 7. Tag and push Docker image to Amazon ECR
      - name: Tag and Push Docker image
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_URI: ${{ secrets.ECR_URI }}
        run: |
          docker tag demo:latest $ECR_URI/demo:latest
          docker push $ECR_URI/demo:latest

      # 8. SSH into EC2, stop and delete existing container, and deploy
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Stop and remove existing Spring Boot container
            docker stop demo-app || true
            docker rm demo-app || true

            # Remove old image
            docker rmi ${{ secrets.ECR_URI }}/demo:latest || true

            # Pull and run new image
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_URI }}
            docker pull ${{ secrets.ECR_URI }}/demo:latest
            docker run -d --name demo-app --link redis -p 8080:8080 ${{ secrets.ECR_URI }}/demo:latest

            # Ensure Redis container is running
            docker ps | grep redis || docker run -d --name redis -p 6379:6379 redis:6.2
